// Shared UI + cart (with variants) (vanilla JS)
(function () {
  if (window.__BP_SHARED_APP_INITIALIZED__) return;
  window.__BP_SHARED_APP_INITIALIZED__ = true;
  // ---------------- Catalog ----------------
  const FALLBACK_CATALOG = {
    "3d-gyro-v1": { name: "Giroscopio decorativo — PLA", priceEUR: 19.90, url: "./product.html?id=3d-gyro-v1" },
    "3d-stand-v1": { name: "Stand modulare per scrivania", priceEUR: 24.50, url: "./product.html?id=3d-stand-v1" },
    "3d-keycap-v1": { name: "Keycap personalizzata", priceEUR: 14.00, url: "./product.html?id=3d-keycap-v1" },
    "print-seri-a2": { name: "Serigrafia A2 — edizione limitata", priceEUR: 35.00, url: "./product.html?id=print-seri-a2" },
    "print-poster-a3": { name: "Poster A3 — grafica studio", priceEUR: 18.00, url: "./product.html?id=print-poster-a3" },
    "tee-logo-v1": { name: "T-shirt serigrafata — Logo", priceEUR: 22.00, url: "./product.html?id=tee-logo-v1" },
    "hoodie-v1": { name: "Felpa — patch serigrafata", priceEUR: 48.00, url: "./product.html?id=hoodie-v1" }
  };

  // Default variants used when adding from listings (home/category grids)
  const FALLBACK_DEFAULT_VARIANTS = {
    "3d-gyro-v1": { material: "PLA", color: "Nero" },
    "3d-stand-v1": { material: "PLA", color: "Nero" },
    "3d-keycap-v1": { material: "PLA", color: "Nero" },

    "print-seri-a2": { format: "A2", paper: "Premium 300g" },
    "print-poster-a3": { format: "A3", paper: "Opaca 200g" },

    "tee-logo-v1": { size: "M", color: "Nero" },
    "hoodie-v1": { size: "M", color: "Nero" }
  };

  function buildCatalogFromProducts(products) {
    const out = {};
    if (!Array.isArray(products)) return out;
    for (const p of products) {
      if (!p || !p.id || !p.name) continue;
      const price = Number(p.price);
      out[p.id] = {
        name: p.name,
        priceEUR: Number.isFinite(price) ? price : 0,
        url: p.url || `./product.html?id=${encodeURIComponent(p.id)}`
      };
    }
    return out;
  }

  function buildDefaultVariantsFromProducts(products) {
    const out = {};
    if (!Array.isArray(products)) return out;
    for (const p of products) {
      if (!p || !p.id) continue;
      const variants = Array.isArray(p.variants) ? p.variants : [];
      const defaults = {};
      for (const v of variants) {
        if (!v || !v.key) continue;
        if (v.default) defaults[v.key] = String(v.default);
        else if (Array.isArray(v.options) && v.options.length) defaults[v.key] = String(v.options[0]);
      }
      out[p.id] = defaults;
    }
    return out;
  }

  const externalProducts = Array.isArray(window.__PRODUCTS_DATA) ? window.__PRODUCTS_DATA : [];
  const dynamicCatalog = buildCatalogFromProducts(externalProducts);
  const dynamicDefaults = buildDefaultVariantsFromProducts(externalProducts);
  const PRODUCT_STATUS_BY_ID = Object.fromEntries(
    externalProducts
      .filter((p) => p && p.id)
      .map((p) => [p.id, String(p.status || (p.available === false ? "out-of-stock" : "available"))])
  );

  const CATALOG = Object.keys(dynamicCatalog).length ? dynamicCatalog : FALLBACK_CATALOG;
  const DEFAULT_VARIANTS = Object.keys(dynamicDefaults).length ? dynamicDefaults : FALLBACK_DEFAULT_VARIANTS;

  function isPurchasableProduct(id) {
    const s = PRODUCT_STATUS_BY_ID[id];
    return !(s === "out-of-stock" || s === "coming-soon");
  }

  const VARIANT_LABELS = {
    material: "Materiale",
    color: "Colore",
    size: "Taglia",
    format: "Formato",
    paper: "Carta"
  };

  const FALLBACK_HOME_EVENTS = [
    { dateLabel: "12 Apr", title: "Open Lab: Stampe 3D", period: "18:30 • Spazio Porto", status: "Aperto", published: true, sortOrder: 10 },
    { dateLabel: "19 Apr", title: "Workshop Serigrafia Base", period: "16:00 • Prenotazione", status: "Posti limitati", published: true, sortOrder: 20 },
    { dateLabel: "26 Apr", title: "Mercatino Autoproduzioni", period: "11:00-20:00 • Cortile", status: "Ingresso libero", published: true, sortOrder: 30 }
  ];

  function formatEUR(value) {
    return new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR" }).format(value);
  }

  function loadStaticJsonSync(path) {
    try {
      const xhr = new XMLHttpRequest();
      xhr.open("GET", path, false);
      xhr.send(null);
      if ((xhr.status >= 200 && xhr.status < 300) || xhr.status === 0) {
        return JSON.parse(xhr.responseText || "null");
      }
    } catch {
      // no-op
    }
    return null;
  }

  const externalEvents = loadStaticJsonSync("./data/events.json");
  const HOME_EVENTS = Array.isArray(externalEvents) && externalEvents.length ? externalEvents : FALLBACK_HOME_EVENTS;

  function escapeHtml(str) {
    return String(str).replace(/[&<>"']/g, (ch) => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
    }[ch]));
  }

  // Product URLs are generated by catalog data (single template page).
  function productUrlForPage(id) {
    const entry = CATALOG[id];
    if (!entry) return "#";
    return entry.url;
  }

  // ---------------- Cart (line items with variants) ----------------
  const CART_KEY_V2 = "cart_v2_session"; // Array<{ id: string, variant: object, qty: number }>
  const CART_KEY_V1 = "cart_v1";
  const CART_WINDOW_FALLBACK_KEY = "bp_cart_v2";
  const CART_SESSION_BOOT_KEY = "bp_cart_session_booted";

  function safeLocalRemove(key) {
    try {
      localStorage.removeItem(key);
    } catch {
      // no-op
    }
  }

  function safeSessionGet(key) {
    try {
      return sessionStorage.getItem(key);
    } catch {
      return null;
    }
  }

  function safeSessionSet(key, value) {
    try {
      sessionStorage.setItem(key, value);
      return true;
    } catch {
      return false;
    }
  }

  function readWindowCartRaw() {
    try {
      const name = String(window.name || "");
      const re = new RegExp(`(?:^|;)${CART_WINDOW_FALLBACK_KEY}=([^;]*)`);
      const m = name.match(re);
      if (!m || !m[1]) return null;
      return decodeURIComponent(m[1]);
    } catch {
      return null;
    }
  }

  function writeWindowCartRaw(raw) {
    try {
      const encoded = encodeURIComponent(raw);
      const token = `${CART_WINDOW_FALLBACK_KEY}=${encoded}`;
      const current = String(window.name || "");
      const re = new RegExp(`(?:^|;)${CART_WINDOW_FALLBACK_KEY}=[^;]*`);
      window.name = re.test(current) ? current.replace(re, token) : (current ? `${current};${token}` : token);
    } catch {
      // no-op
    }
  }

  function normalizeCartItems(arr) {
    if (!Array.isArray(arr)) return [];
    const merged = new Map();
    arr.forEach((it) => {
      const normalized = {
        id: String(it.id || ""),
        variant: normalizeVariant(it.variant || {}),
        qty: Math.max(1, Number(it.qty || 1))
      };
      if (!normalized.id || !CATALOG[normalized.id]) return;

      const key = lineKey(normalized.id, normalized.variant);
      const existing = merged.get(key);
      if (existing) {
        existing.qty += normalized.qty;
        return;
      }
      merged.set(key, normalized);
    });
    return Array.from(merged.values());
  }

  function updateInternalCartLinks() {
    document.querySelectorAll("a[href]").forEach((a) => {
      const href = a.getAttribute("href");
      if (!href || href.startsWith("#") || href.startsWith("mailto:") || href.startsWith("tel:") || href.startsWith("javascript:")) return;

      let url;
      try {
        url = new URL(href, window.location.href);
      } catch {
        return;
      }
      if (!/\.html$/i.test(url.pathname)) return;
      url.searchParams.delete("_cart");

      a.setAttribute("href", url.pathname + url.search + url.hash);
    });
  }

  function clearLegacyCartUrlParam() {
    if (!window.history.replaceState) return;
    try {
      const url = new URL(window.location.href);
      if (!url.searchParams.has("_cart")) return;
      url.searchParams.delete("_cart");
      window.history.replaceState(null, "", url.pathname + url.search + url.hash);
    } catch {
      // no-op
    }
  }

  function normalizeVariant(v) {
    const out = {};
    if (!v || typeof v !== "object") return out;
    for (const [k, val] of Object.entries(v)) {
      if (val === null || val === undefined) continue;
      const s = String(val).trim();
      if (!s) continue;
      out[k] = s;
    }
    return out;
  }

  function bootstrapCartSession() {
    if (safeSessionGet(CART_SESSION_BOOT_KEY)) return;
    safeSessionSet(CART_SESSION_BOOT_KEY, "1");
    safeSessionSet(CART_KEY_V2, "[]");
    safeLocalRemove(CART_KEY_V2);
    safeLocalRemove(CART_KEY_V1);
    writeWindowCartRaw("[]");
    clearLegacyCartUrlParam();
    updateInternalCartLinks();
  }

  function lineKey(id, variant) {
    const v = normalizeVariant(variant);
    const keys = Object.keys(v).sort();
    const sig = keys.map(k => `${k}=${v[k]}`).join(";");
    return `${id}|${sig}`;
  }

  function readCartV2() {
    try {
      const raw = safeSessionGet(CART_KEY_V2) || readWindowCartRaw();
      if (!raw) return null;
      return normalizeCartItems(JSON.parse(raw));
    } catch {
      return null;
    }
  }

  function writeCartV2(items) {
    const normalized = normalizeCartItems(items);
    const raw = JSON.stringify(normalized);
    safeSessionSet(CART_KEY_V2, raw);
    writeWindowCartRaw(raw);
    updateInternalCartLinks();
  }

  function readCart() {
    bootstrapCartSession();
    return readCartV2() || [];
  }

  function cartCount(items) {
    return items.reduce((sum, it) => sum + (it.qty || 0), 0);
  }

  function cartSubtotal(items) {
    return items.reduce((sum, it) => {
      const p = CATALOG[it.id];
      if (!p) return sum;
      return sum + p.priceEUR * it.qty;
    }, 0);
  }

  function upsertLine(items, id, variant, qtyDelta) {
    const v = normalizeVariant(variant);
    const key = lineKey(id, v);
    const idx = items.findIndex(it => lineKey(it.id, it.variant) === key);
    if (idx >= 0) {
      items[idx].qty = Math.max(1, items[idx].qty + qtyDelta);
      return items;
    }
    items.push({ id, variant: v, qty: Math.max(1, qtyDelta) });
    return items;
  }

  function setLineQty(items, key, newQty) {
    const idx = items.findIndex(it => lineKey(it.id, it.variant) === key);
    if (idx < 0) return items;
    const q = Number(newQty || 1);
    if (q <= 0) items.splice(idx, 1);
    else items[idx].qty = Math.max(1, q);
    return items;
  }

  function incLine(items, key) {
    const idx = items.findIndex(it => lineKey(it.id, it.variant) === key);
    if (idx < 0) return items;
    items[idx].qty += 1;
    return items;
  }

  function decLine(items, key) {
    const idx = items.findIndex(it => lineKey(it.id, it.variant) === key);
    if (idx < 0) return items;
    items[idx].qty -= 1;
    if (items[idx].qty <= 0) items.splice(idx, 1);
    return items;
  }

  function clearCart() {
    writeCartV2([]);
    renderAllCartUI();
  }

  function renderCartCounts() {
    const items = readCart();
    const n = cartCount(items);
    document.querySelectorAll("[data-cart-count]").forEach(el => el.textContent = String(n));
  }

  function variantSummary(variant) {
    const v = normalizeVariant(variant);
    const keys = Object.keys(v).filter(k => v[k]).sort();
    if (!keys.length) return "";
    return keys.map(k => `${VARIANT_LABELS[k] || k}: ${v[k]}`).join(" • ");
  }

  function renderHomeEvents() {
    const list = document.getElementById("homeEventsList");
    if (!list) return;
    list.innerHTML = "";
    const events = HOME_EVENTS
      .filter((ev) => ev && ev.published !== false)
      .sort((a, b) => Number(a.sortOrder || 0) - Number(b.sortOrder || 0));

    for (const ev of events) {
      const item = document.createElement("article");
      item.className = "event-item";
      const date = ev.dateLabel || ev.date || "";
      const meta = ev.period || ev.meta || ev.description || "";
      const status = ev.status || (ev.published === false ? "Bozza" : "Attivo");
      item.innerHTML = `
        <p class="event-item__date">${escapeHtml(date)}</p>
        <div>
          <h3 class="event-item__title">${escapeHtml(ev.title)}</h3>
          <p class="event-item__meta">${escapeHtml(meta)}</p>
        </div>
        <span class="event-item__tag">${escapeHtml(status)}</span>
      `;
      list.appendChild(item);
    }
  }

  // ---------------- Drawers ----------------
  const overlay = document.getElementById("overlay");
  const menuDrawer = document.getElementById("menuDrawer");
  const cartDrawer = document.getElementById("cartDrawer");

  const menuBtn = document.getElementById("menuBtn");
  const menuCloseBtn = document.getElementById("menuCloseBtn");

  const cartBtn = document.getElementById("cartBtn");
  const cartCloseBtn = document.getElementById("cartCloseBtn");
  const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  let overlayHideTimer = null;

  function setExpanded(btn, expanded) {
    if (btn) btn.setAttribute("aria-expanded", expanded ? "true" : "false");
  }

  function showOverlay() {
    if (!overlay) return;
    if (overlayHideTimer) {
      clearTimeout(overlayHideTimer);
      overlayHideTimer = null;
    }
    overlay.hidden = false;
    requestAnimationFrame(() => overlay.classList.add("is-active"));
  }

  function hideOverlayIfNoDrawerOpen() {
    if (!overlay) return;
    const menuOpen = menuDrawer && menuDrawer.classList.contains("is-open");
    const cartOpen = cartDrawer && cartDrawer.classList.contains("is-open");
    if (menuOpen || cartOpen) {
      overlay.hidden = false;
      overlay.classList.add("is-active");
      return;
    }
    overlay.classList.remove("is-active");
    overlayHideTimer = window.setTimeout(() => {
      overlay.hidden = true;
      overlayHideTimer = null;
    }, 240);
  }

  function openDrawer(drawer, btn) {
    if (!drawer) return;
    if (drawer === menuDrawer && cartDrawer && cartDrawer.classList.contains("is-open")) {
      closeDrawer(cartDrawer, cartBtn);
    }
    if (drawer === cartDrawer && menuDrawer && menuDrawer.classList.contains("is-open")) {
      closeDrawer(menuDrawer, menuBtn);
    }
    drawer.classList.add("is-open");
    drawer.setAttribute("aria-hidden", "false");
    setExpanded(btn, true);
    showOverlay();
    document.body.style.overflow = "hidden";
  }

  function closeDrawer(drawer, btn) {
    if (!drawer) return;
    drawer.classList.remove("is-open");
    drawer.setAttribute("aria-hidden", "true");
    setExpanded(btn, false);
    hideOverlayIfNoDrawerOpen();
    const menuOpen = menuDrawer && menuDrawer.classList.contains("is-open");
    const cartOpen = cartDrawer && cartDrawer.classList.contains("is-open");
    if (!(menuOpen || cartOpen)) document.body.style.overflow = "";
  }

  function closeAllDrawers() {
    closeDrawer(menuDrawer, menuBtn);
    closeDrawer(cartDrawer, cartBtn);
  }

  if (menuBtn) menuBtn.addEventListener("click", () => openDrawer(menuDrawer, menuBtn));
  if (menuCloseBtn) menuCloseBtn.addEventListener("click", () => closeDrawer(menuDrawer, menuBtn));

  if (cartBtn) cartBtn.addEventListener("click", () => {
    renderCartDrawer();
    openDrawer(cartDrawer, cartBtn);
  });
  if (cartCloseBtn) cartCloseBtn.addEventListener("click", () => closeDrawer(cartDrawer, cartBtn));

  if (overlay) overlay.addEventListener("click", closeAllDrawers);

  document.addEventListener("keydown", (ev) => {
    if (ev.key === "Escape") closeAllDrawers();
  });

  // Close menu drawer when clicking any navigation link inside it
  if (menuDrawer) {
    menuDrawer.addEventListener("click", (ev) => {
      const a = ev.target.closest("a");
      if (a) closeDrawer(menuDrawer, menuBtn);
    });
  }

  // Mark current page in drawer navigation.
  (function markCurrentMenuLink() {
    function normalizePath(pathname) {
      const clean = pathname.replace(/\/index\.html$/, "/").replace(/\/+$/, "/");
      return clean === "" ? "/" : clean;
    }

    function menuKey(url) {
      const path = normalizePath(url.pathname);
      if (!/\/category\.html$/.test(path)) return path;
      const category = (url.searchParams.get("category") || "").trim();
      return `${path}?category=${category}`;
    }

    const currentUrl = new URL(window.location.href);
    const current = menuKey(currentUrl);
    document.querySelectorAll(".menu-link").forEach((link) => {
      const href = link.getAttribute("href");
      if (!href) return;

      let url;
      try {
        url = new URL(href, window.location.href);
      } catch {
        return;
      }
      const isCurrent = menuKey(url) === current;

      if (isCurrent) {
        link.setAttribute("aria-current", "page");
        const small = link.querySelector("small");
        if (small) small.textContent = "Sei qui";
      } else {
        link.removeAttribute("aria-current");
      }
    });
  })();

  (function initRevealAnimations() {
    const revealEls = Array.from(document.querySelectorAll("[data-reveal]"));
    if (!revealEls.length) return;

    const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const showNow = (el) => {
      el.classList.add("is-visible");
      el.style.transitionDelay = "";
    };

    if (reduceMotion || !("IntersectionObserver" in window)) {
      revealEls.forEach(showNow);
      return;
    }

    const observer = new IntersectionObserver((entries, obs) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        const el = entry.target;
        const delay = Number(el.getAttribute("data-reveal-delay") || 0);
        if (delay > 0) el.style.transitionDelay = `${delay}ms`;
        el.classList.add("is-visible");
        obs.unobserve(el);
      });
    }, { threshold: 0.16, rootMargin: "0px 0px -8% 0px" });

    revealEls.forEach((el) => observer.observe(el));
  })();

  // Home-only: data-scroll buttons inside menu
  document.querySelectorAll("[data-scroll]").forEach((btn) => {
    btn.addEventListener("click", () => {
      const target = btn.getAttribute("data-scroll");
      closeDrawer(menuDrawer, menuBtn);
      if (!target) return;
      const el = document.querySelector(target);
      if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  });

  // ---------------- Add to cart (from listings & product pages) ----------------
  function getQtyFromButton(btn) {
    const from = btn.getAttribute("data-qty-from");
    if (from === "input") {
      const root = btn.closest(".product-info") || btn.closest("main") || document;
      const input = root.querySelector("[data-qty-input]");
      if (input) return Math.max(1, Number(input.value || 1));
    }
    return 1;
  }

  function getVariantsFromPage(productId) {
    // read all fields with [data-variant] (only meaningful on product pages)
    const variant = {};
    document.querySelectorAll("[data-variant]").forEach(el => {
      const key = el.getAttribute("data-variant");
      if (!key) return;
      const val = (el.value || "").trim();
      if (!val) return;
      variant[key] = val;
    });

    // Merge defaults for missing keys
    const def = DEFAULT_VARIANTS[productId] || {};
    for (const [k, v] of Object.entries(def)) {
      if (!variant[k]) variant[k] = v;
    }
    return normalizeVariant(variant);
  }

  function showAddToast(productId, qty) {
    const p = CATALOG[productId];
    if (!p) return;
    const toast = document.createElement("div");
    toast.className = "cart-toast";
    toast.setAttribute("role", "status");
    toast.setAttribute("aria-live", "polite");
    toast.textContent = `${p.name} x${qty} aggiunto al carrello`;
    document.body.appendChild(toast);
    requestAnimationFrame(() => toast.classList.add("is-visible"));
    window.setTimeout(() => {
      toast.classList.remove("is-visible");
      window.setTimeout(() => toast.remove(), 220);
    }, 1500);
  }

  function triggerAddToCartFeedback(sourceEl, productId, qty) {
    showAddToast(productId, qty);

    if (cartBtn) {
      cartBtn.classList.remove("cart-btn-pulse");
      void cartBtn.offsetWidth;
      cartBtn.classList.add("cart-btn-pulse");
      window.setTimeout(() => cartBtn.classList.remove("cart-btn-pulse"), 430);
    }

    document.querySelectorAll("[data-cart-count]").forEach((el) => {
      el.classList.remove("cart-count-bump");
      void el.offsetWidth;
      el.classList.add("cart-count-bump");
      window.setTimeout(() => el.classList.remove("cart-count-bump"), 380);
    });

    if (reduceMotion || !sourceEl || !cartBtn) return;

    const from = sourceEl.getBoundingClientRect();
    const to = cartBtn.getBoundingClientRect();
    const dot = document.createElement("span");
    dot.className = "add-fx-dot";
    const startX = from.left + from.width / 2;
    const startY = from.top + from.height / 2;
    dot.style.left = `${startX - 5}px`;
    dot.style.top = `${startY - 5}px`;
    document.body.appendChild(dot);

    const dx = to.left + to.width / 2 - startX;
    const dy = to.top + to.height / 2 - startY;
    if (typeof dot.animate === "function") {
      dot.animate(
        [
          { transform: "translate3d(0, 0, 0) scale(1)", opacity: 0.96 },
          { transform: `translate3d(${dx}px, ${dy}px, 0) scale(.46)`, opacity: 0.08 }
        ],
        { duration: 580, easing: "cubic-bezier(.22,.61,.36,1)", fill: "forwards" }
      ).onfinish = () => dot.remove();
    } else {
      requestAnimationFrame(() => {
        dot.classList.add("is-flying");
        dot.style.transform = `translate3d(${dx}px, ${dy}px, 0) scale(.55)`;
      });
      window.setTimeout(() => dot.remove(), 620);
    }
  }

  function addToCart(productId, qty, variantOverride, sourceEl) {
    const items = readCart();
    const variant = normalizeVariant(variantOverride || DEFAULT_VARIANTS[productId] || {});
    upsertLine(items, productId, variant, qty);
    writeCartV2(items);
    renderAllCartUI();
    triggerAddToCartFeedback(sourceEl, productId, qty);
  }

  document.addEventListener("click", (ev) => {
    const btn = ev.target.closest("[data-add-to-cart]");
    if (!btn) return;
    const id = btn.getAttribute("data-id");
    if (!id || !CATALOG[id]) return;
    if (!isPurchasableProduct(id)) return;

    const qty = getQtyFromButton(btn);

    // On product pages, use page variants
    const bodyPid = document.body.getAttribute("data-product-id");
    const isProductPage = bodyPid && bodyPid === id;
    const variant = isProductPage ? getVariantsFromPage(id) : (DEFAULT_VARIANTS[id] || {});

    addToCart(id, qty, variant, btn);
  });

  // Initialize variant selects on product pages (defaults)
  (function initVariantsDefaults() {
    const pid = document.body.getAttribute("data-product-id");
    if (!pid || !DEFAULT_VARIANTS[pid]) return;
    const def = DEFAULT_VARIANTS[pid];
    document.querySelectorAll("[data-variant]").forEach(el => {
      const k = el.getAttribute("data-variant");
      if (!k) return;
      if (!el.value && def[k]) el.value = def[k];
      // also set if current value not in options (edge cases)
      if (def[k]) el.value = def[k];
    });
  })();

  // Qty stepper on product pages
  document.addEventListener("click", (ev) => {
    const decBtn = ev.target.closest("[data-qty-dec]");
    const incBtn = ev.target.closest("[data-qty-inc]");
    if (!decBtn && !incBtn) return;

    const root = (decBtn || incBtn).closest(".qty-stepper") || document;
    const input = root.querySelector("[data-qty-input]");
    if (!input) return;
    const current = Math.max(1, Number(input.value || 1));
    input.value = String(Math.max(1, current + (incBtn ? 1 : -1)));
  });

  document.addEventListener("input", (ev) => {
    const input = ev.target.closest("[data-qty-input]");
    if (!input) return;
    const cleaned = String(input.value || "").replace(/[^\d]/g, "");
    input.value = cleaned || "1";
  });

  document.addEventListener("change", (ev) => {
    const input = ev.target.closest("[data-qty-input]");
    if (!input) return;
    const n = Math.max(1, Number(input.value || 1));
    input.value = String(n);
  });

  document.addEventListener("wheel", (ev) => {
    const input = ev.target.closest("[data-qty-input]");
    if (!input) return;
    // Prevent accidental quantity changes while scrolling.
    ev.preventDefault();
  }, { passive: false });

  // ---------------- Cart Drawer render ----------------
  const cartItemsEl = document.getElementById("cartItems");
  const cartSubtotalEl = document.getElementById("cartSubtotal");
  const cartEmptyNote = document.getElementById("cartEmptyNote");
  const cartClearBtn = document.getElementById("cartClearBtn");

  function renderCartDrawer() {
    if (!cartItemsEl || !cartSubtotalEl) return;
    const items = readCart();
    renderCartList(items, cartItemsEl, cartEmptyNote, cartSubtotalEl);
    renderCartCounts();
  }

  if (cartClearBtn) cartClearBtn.addEventListener("click", clearCart);

  // ---------------- Cart page render ----------------
  const cartPageItems = document.getElementById("cartPageItems");
  const cartPageSubtotal = document.getElementById("cartPageSubtotal");
  const cartPageEmpty = document.getElementById("cartPageEmpty");
  const cartPageClearBtn = document.getElementById("cartPageClearBtn");

  function buildCartItemMarkup(item) {
    const product = CATALOG[item.id];
    if (!product) return null;

    const key = lineKey(item.id, item.variant);
    const url = productUrlForPage(item.id);
    const price = formatEUR(product.priceEUR);
    const line = formatEUR(product.priceEUR * item.qty);
    const vSum = variantSummary(item.variant);

    const div = document.createElement("div");
    div.className = "cart-item";
    div.innerHTML = `
      <div class="cart-item__main">
        <div class="cart-item__top">
          <h4><a href="${url}">${escapeHtml(product.name)}</a></h4>
          <b class="cart-item__line">${escapeHtml(line)}</b>
        </div>
        <div class="meta">${escapeHtml(vSum || "Configurazione standard")}</div>
        <div class="meta meta--sub">${escapeHtml(price)} cad.</div>
      </div>
      <div class="qty">
        <button type="button" data-cart-remove="${escapeHtml(key)}" aria-label="Rimuovi">×</button>
        <button type="button" data-cart-dec="${escapeHtml(key)}" aria-label="Diminuisci">−</button>
        <span>${item.qty}</span>
        <button type="button" data-cart-inc="${escapeHtml(key)}" aria-label="Aumenta">+</button>
      </div>
    `;
    return div;
  }

  function renderCartList(items, container, emptyNoteEl, subtotalEl) {
    if (!container || !subtotalEl) return;

    container.innerHTML = "";
    const empty = items.length === 0;
    if (emptyNoteEl) emptyNoteEl.hidden = !empty;

    items.forEach((item) => {
      const el = buildCartItemMarkup(item);
      if (el) container.appendChild(el);
    });

    subtotalEl.textContent = formatEUR(cartSubtotal(items));
  }

  function renderCartPage() {
    if (!cartPageItems || !cartPageSubtotal) return;
    const items = readCart();
    renderCartList(items, cartPageItems, cartPageEmpty, cartPageSubtotal);
    renderCartCounts();
  }

  if (cartPageClearBtn) cartPageClearBtn.addEventListener("click", clearCart);

  // Unified +/- handling for drawer & page
  document.addEventListener("click", (ev) => {
    const inc = ev.target.closest("[data-cart-inc]");
    const dec = ev.target.closest("[data-cart-dec]");
    const remove = ev.target.closest("[data-cart-remove]");
    if (!inc && !dec && !remove) return;

    const key = (inc || dec || remove).getAttribute(
      inc ? "data-cart-inc" : (dec ? "data-cart-dec" : "data-cart-remove")
    );
    if (!key) return;

    const items = readCart();
    if (inc) incLine(items, key);
    else if (dec) decLine(items, key);
    else setLineQty(items, key, 0);

    writeCartV2(items);
    renderAllCartUI();
  });

  function renderAllCartUI() {
    renderCartCounts();
    renderCartDrawer();
    renderCartPage();
    updateInternalCartLinks();
  }

  // Initial render
  renderAllCartUI();
  renderHomeEvents();

})();
